ahg_voice_describe:
  url: /ahgVoice/describeImage
  param: { module: ahgVoice, action: describeImage }
  requirements:
    sf_method: [POST]

ahg_voice_save_description:
  url: /ahgVoice/saveDescription
  param: { module: ahgVoice, action: saveDescription }
  requirements:
    sf_method: [POST]

ahg_voice_describe_object:
  url: /ahgVoice/describeObject
  param: { module: ahgVoice, action: describeObject }
  requirements:
    sf_method: [POST]

ahg_voice_get_settings:
  url: /ahgVoice/getSettings
  param: { module: ahgVoice, action: getSettings }
