term_edit_override:
  class: QubitResourceRoute
  url: /term/:slug/edit
  param: { module: termTaxonomy, action: edit }
  requirements: { slug: "[a-zA-Z0-9_-]+" }

term_delete_override:
  class: QubitResourceRoute
  url: /term/:slug/delete
  param: { module: termTaxonomy, action: delete }
  requirements: { slug: "[a-zA-Z0-9_-]+" }

term_add:
  url: /term/add
  class: AddActionRoute
  param: { module: term, action: edit }

term_browse_override:
  class: QubitResourceRoute
  url: /term/:slug
  param: { module: termTaxonomy, action: index }
  requirements: { slug: "(?!add$)[a-zA-Z0-9_-]+" }

taxonomy_browse_override:
  url: /taxonomy/:id
  param: { module: termTaxonomy, action: taxonomyIndex }
  requirements: { id: \d+ }
