term_browse_override:
  class: QubitResourceRoute
  url: /term/:slug
  param: { module: termTaxonomy, action: index }
  requirements: { slug: "[a-zA-Z0-9_-]+" }

taxonomy_browse_override:
  url: /taxonomy/:id
  param: { module: termTaxonomy, action: taxonomyIndex }
  requirements: { id: \d+ }
