# AHG Feedback Plugin Routes

ahg_feedback_browse:
  url: /feedback
  param: { module: feedback, action: browse }

ahg_feedback_general:
  url: /feedback/general
  param: { module: feedback, action: general }

ahg_feedback_submit:
  url: /informationobject/:slug/feedback
  param: { module: feedback, action: submit }

ahg_feedback_edit:
  url: /feedback/:id/edit
  param: { module: feedback, action: edit }
  requirements:
    id: \d+

ahg_feedback_delete:
  url: /feedback/:id/delete
  param: { module: feedback, action: delete }
  requirements:
    id: \d+

ahg_feedback_view:
  url: /feedback/:id
  param: { module: feedback, action: view }
  requirements:
    id: \d+
