all:
  .settings:
    enabled_modules:
      - spectrumReports
      - threeDReports
      - ahgSettings
      - informationobject
      - label

# Vendor module settings
vendor:
  enabled_modules: [vendor]
