all:
  .settings:
    enabled_modules:
      - api
      - identifierApi
      - informationobject
      - spectrumReports
      - threeDReports
      - accession
      - actor
      - admin
      - browse
      - clipboard
      - default
      - digitalobject
      - function
      - jobs
      - menu
      - object
      - physicalobject
      - repository
      - right
      - rightsholder
      - search
      - staticpage
      - taxonomy
      - term
      - user

vendor:
  enabled_modules: [vendor]
