# ahgDisplayPlugin routes - using /glam prefix to avoid conflicts

# Override default informationobject browse to use GLAM browse
informationobject_browse_override:
  url: /informationobject/browse
  param: { module: display, action: browse }

glam_index:
  url: /glam
  param: { module: display, action: index }

glam_profiles:
  url: /glam/profiles
  param: { module: display, action: profiles }

glam_levels:
  url: /glam/levels
  param: { module: display, action: levels }

glam_fields:
  url: /glam/fields
  param: { module: display, action: fields }

glam_set_type:
  url: /glam/setType
  param: { module: display, action: setType }

glam_assign_profile:
  url: /glam/assignProfile
  param: { module: display, action: assignProfile }

glam_bulk_set_type:
  url: /glam/bulkSetType
  param: { module: display, action: bulkSetType }

glam_search:
  url: /glam/search
  param: { module: displaySearch, action: search }

glam_search_results:
  url: /glam/search/results
  param: { module: displaySearch, action: browse }

glam_browse:
  url: /glam/browse
  param: { module: display, action: browse }

glam_browse_ajax:
  url: /glam/browseAjax
  param: { module: display, action: browseAjax }

glam_print:
  url: /glam/print
  param: { module: display, action: print }

glam_export_csv:
  url: /glam/exportCsv
  param: { module: display, action: exportCsv }

glam_change_type:
  url: /glam/changeType
  param: { module: display, action: changeType }

# User browse settings
glam_browse_settings:
  url: /glam/settings
  param: { module: display, action: browseSettings }

glam_toggle_glam_browse:
  url: /glam/toggleGlamBrowse
  param: { module: display, action: toggleGlamBrowse }

glam_save_browse_settings:
  url: /glam/saveBrowseSettings
  param: { module: display, action: saveBrowseSettings }

glam_get_browse_settings:
  url: /glam/getBrowseSettings
  param: { module: display, action: getBrowseSettings }

glam_reset_browse_settings:
  url: /glam/resetBrowseSettings
  param: { module: display, action: resetBrowseSettings }

# Treeview routes - override base AtoM informationobject treeview
treeview_override:
  class: QubitResourceRoute
  url: /:slug/treeView
  param: { module: treeview, action: view }
  requirements: { slug: "[a-zA-Z0-9_-]+" }

treeview_sort_override:
  class: QubitResourceRoute
  url: /:slug/treeViewSort
  param: { module: treeview, action: sort }
  requirements: { slug: "[a-zA-Z0-9_-]+" }
