# TIFF to PDF Merge Routes

tiffpdfmerge:
  url: /tiff-pdf-merge
  param: { module: tiffpdfmerge, action: index }

tiffpdfmerge_with_object:
  url: /tiff-pdf-merge/:informationObject
  param: { module: tiffpdfmerge, action: index }

tiffpdfmerge_create:
  url: /tiff-pdf-merge/create
  param: { module: tiffpdfmerge, action: create }

tiffpdfmerge_upload:
  url: /tiff-pdf-merge/upload
  param: { module: tiffpdfmerge, action: upload }

tiffpdfmerge_reorder:
  url: /tiff-pdf-merge/reorder
  param: { module: tiffpdfmerge, action: reorder }

tiffpdfmerge_remove_file:
  url: /tiff-pdf-merge/remove-file
  param: { module: tiffpdfmerge, action: removeFile }

tiffpdfmerge_get_job:
  url: /tiff-pdf-merge/job/:job_id
  param: { module: tiffpdfmerge, action: getJob }

tiffpdfmerge_process:
  url: /tiff-pdf-merge/process
  param: { module: tiffpdfmerge, action: process }

tiffpdfmerge_download:
  url: /tiff-pdf-merge/download/:job_id
  param: { module: tiffpdfmerge, action: download }

tiffpdfmerge_delete:
  url: /tiff-pdf-merge/delete
  param: { module: tiffpdfmerge, action: delete }
